apiVersion: v1
kind: Secret
metadata:
  name: policyservice-secrets
  namespace: policyservice
type: Opaque
stringData:
  KEYVAULT_NAME: "kv-policyservice-dev"
  ASPNETCORE_ENVIRONMENT: "Production"
  ASPNETCORE_URLS: "http://+:8080"
