apiVersion: v1
kind: Service
metadata:
  name: policyservice-api
  namespace: policyservice
  labels:
    app: policyservice-api
spec:
  type: LoadBalancer
  selector:
    app: policyservice-api
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
