apiVersion: v1
kind: ServiceAccount
metadata:
  name: policyservice-identity
  namespace: policyservice
  annotations:
    azure.workload.identity/client-id: "0473f21c-8e43-479c-8c4e-3cd749e1e243"
  labels:
    azure.workload.identity/use: "true"
